FROM rust:1.80

# 必要なツールとライブラリをインストール
RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    build-essential \
    && apt-get clean \
    mkdir -p /var/lib/haproxy && chmod 755 /var/lib/haproxy
# 作業ディレクトリを設定
WORKDIR /app

# Cargo.tomlとCargo.lockをコピー
COPY Cargo.toml Cargo.lock ./

# ソースコードをコピー
COPY ./src ./src

# リリースビルド
RUN cargo build --release && \
# バイナリを /usr/local/bin にコピー
    cp target/release/proxyserver /usr/local/bin/proxyserver
