global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'otdm'

rule_files:

scrape_configs:
  - job_name: hostnode
    static_configs:
      - targets: ['10.0.0.10:9100']
  - job_name: cAdvisor
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: site_health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://otdm.dev
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115