# このファイルを実行する前にすべき事
# 先にビルドしておくものはこれに記載されたイメージ名で作成する
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    user: "1000:1000"

  vpn:
    build:
      context: .
      dockerfile: ./vpn/Dockerfile
    user: "1000:1000"

  proxy:
    build:
      context: .
      dockerfile: ./proxy/Dockerfile
    user: "1000:1000"