---
# このファイルを実行する前にすべき事
# 先にビルドしておくものはこれに記載されたイメージ名で作成する
# テスト時に実行サービスがない場合エラーになるのでコメントアウトする


services:
  api:
    build:
      context: /home/ubuntu/otedama/docker-compose/api
      dockerfile: ./Dockerfile
    user: "1000:1000"

  vpn:
    build:
      context: /home/ubuntu/otedama/docker-compose/vpn
      dockerfile: ./Dockerfile
  #   user: "1000:1000"
  #  ↑一般ユーザだと動作しない↑VPNServerは特権での実行で問題が無いため削除

  proxy:
    build:
      context: /home/ubuntu/otedama/docker-compose/proxy
      dockerfile: ./Dockerfile
  #  user: "1000:1000"

