apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    io.kompose.service: proxy
