[package]
name = "apiclient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3"
tokio-tungstenite = "0.23.1"
url = "2"
