FROM almalinux:9.5

# 必要なツールをインストール
RUN dnf update -y \
    dnf install -y \
        gcc \ 
        openssl-devel \ 
        pkgconfig \
        python3-pip 

# Pythonパッケージcqlshをインストール
RUN pip install cqlsh

# 作業ディレクトリを設定
WORKDIR /app

# バイナリをコピー
COPY rust/build/apiserver ./apiserver

# 実行コマンド
CMD ["./apiserver"]