[package]
name = "proxyserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures-util = "0.3"
once_cell = "1.8"
lazy_static = "1.4"
