FROM almalinux:9.5

# 必要なツールをインストール
RUN dnf update -y \
    dnf install -y \
        gcc \ 
        openssl-devel \ 
        dnf install -y pkgconfig 
RUN dnf install -y python3-pip 

# Pythonパッケージcqlshをインストール
RUN pip install cqlsh

# Rust環境のパスを設定
ENV PATH="/root/.cargo/bin:${PATH}"
